"use strict";
//q23
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
let car1 = 'subaru';
console.log("Is car1 == 'subaru'? I predict True.");
console.log(car != 'subaru');
let car2 = 'subaru';
console.log("Is car2 != 'subaru'? I predict True.");
console.log(car2 == 'subaru');
let car3 = 'subaru';
console.log("Is car3 != 'subaru'? I predict True.");
console.log(car3 != 'subaru');
let car4 = 'subaru';
console.log("Is car4 == 'subaru'? I predict True.");
console.log(car4 == 'subaru');
let car5 = 'subaru';
console.log("Is car5 == 'subaru'? I predict True.");
console.log(car5 != 'subaru');
let car6 = 'subaru';
console.log("Is car6 != 'subaru'? I predict false.");
console.log(car6 != 'subaru');
let car7 = 'subaru';
console.log("Is car7 == 'subaru'? I predict false.");
console.log(car7 == 'subaru');
let car8 = 'subaru';
console.log("Is car8 == 'subaru'? I predict false.");
console.log(car8 != 'subaru');
let car9 = 'subaru';
console.log("Is car9 != 'subaru'? I predict false.");
console.log(car9 == 'subaru');
